#! /bin/sh

# ╔╗ ╔═╗╔═╗╦ ╦╔╦╗╦═╗╔═╗
# ╠╩╗╚═╗╠═╝║║║║║║╠╦╝║  
# ╚═╝╚═╝╩  ╚╩╝╩ ╩╩╚═╚═╝

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1


#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

# Default 1 monitor with 6 workspaces
for monitor in "$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)"; do
	bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6'
	#bspc monitor "$monitor" -d '' '' '' '' '' ''
done

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# source the colors.
. "${HOME}/.cache/wal/colors.sh"
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

# Fix Cursor
xsetroot -cursor_name left_ptr &

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &
picom --config ~/.config/picom/picom.conf &
wal -R &
xrdb -merge /home/woozy/.cache/wal/colors.Xresources
ln -sf    "${HOME}/.cache/wal/dunstrc"    "${HOME}/.config/dunst/dunstrc"
dunst -conf ~/.config/dunst/dunstrc &
$HOME/.config/polybar/launch.sh &
